### ISSUE TITLE
Move tests in a sub-project (or 2: one for gtest, one for gmock)

### ISSUE THREAD

**Issue by Klaim** [Klaim/gtest-build2#2]
Cannot be done as long as the submodule directory, therefore the source files of the tests, are outside of the sub-project directory.

Related issue, maybe will lead to a solution: https://github.com/build2/build2/issues/26

**Comment by Swat-SomeBug** [comment]
@Klaim would you be open to a PR for this? I was able to create sub-projects for `gtest`, `gtest-tests`, `gtest-samples`, `gmock` and `gmock-tests`.
Because of the issue google/googletest#2269 in upstream when compiling with GCC > 9, I had to upgrade to release-1.10.0.

**Comment by Klaim** [comment]
Yes of course! I will review your PR tomorrow (I need to go to sleep now). Thanks for your effort!
